# slurm++ demo cluster configuration
ClusterName=demo-cluster
SlurmctldHost=slurm-node

AuthType=auth/munge
SlurmUser=slurm
MpiDefault=none

# Use linuxproc instead of cgroup — works in Docker without privileged mode
ProctrackType=proctrack/linuxproc
TaskPlugin=task/none

ReturnToService=2

SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/spool/slurmctld

SwitchType=switch/none
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory


SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log

# 1 node with 8 CPUs, 8GB RAM
NodeName=slurm-node CPUs=8 RealMemory=8000 State=UNKNOWN

PartitionName=general  Nodes=slurm-node Default=YES  MaxTime=24:00:00 State=UP
PartitionName=gpu      Nodes=slurm-node Default=NO   MaxTime=08:00:00 State=UP
PartitionName=debug    Nodes=slurm-node Default=NO   MaxTime=00:30:00 State=UP
